version: '3.8'

services:
  inference-api:
    build:
      context: ../apps/inference-api
      dockerfile: Dockerfile
    container_name: tru-v2-inference-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=${MODEL_PATH:-Qwen/Qwen3-VL-8B-Instruct}
      - MODEL_BACKEND=${MODEL_BACKEND:-hf}
      - USE_FLASH_ATTN=${USE_FLASH_ATTN:-false}
      - CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - model-cache:/root/.cache/huggingface
      - ../apps/inference-api/app:/app/app  # Mount for hot-reload during development
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Placeholder for NextJS frontend
  web:
    image: node:20-alpine
    container_name: tru-v2-web
    working_dir: /app
    command: sh -c "echo 'NextJS frontend placeholder - to be implemented' && tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - ../apps/web:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://inference-api:8000
    depends_on:
      - inference-api

volumes:
  model-cache:
    driver: local

